Repository SCBJ-7/SCBJ-BE, pull requests merged in 2024-01, with the labels that each got.

#31 Github Actions와 Docker를 이용한 cd작업 (배포 서버 환경 세팅 완료)
  .github/workflows/deploy.yml
  Dockerfile
  src/test/resources/application.yml
Labels: 🛠feature

#33 Docker file 수정
  Dockerfile
Labels: 🛠feature

#34 Feature/#14 create entity
  src/main/java/com/yanolja/scbj/ScbjApplication.java
  src/main/java/com/yanolja/scbj/domain/alarm/entity/Alarm.java
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/Hotel.java
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/HotelRoomImage.java
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/HotelRoomPrice.java
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/RefundPolicy.java
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/Room.java
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/RoomTheme.java
  src/main/java/com/yanolja/scbj/domain/hotelRoom/repository/HotelRoomImageRepository.java
  src/main/java/com/yanolja/scbj/domain/hotelRoom/repository/HotelRoomPriceRepository.java
  src/main/java/com/yanolja/scbj/domain/hotelRoom/repository/HotelRoomRepository.java
  src/main/java/com/yanolja/scbj/domain/hotelRoom/repository/RefundPolicyRepository.java
  src/main/java/com/yanolja/scbj/domain/hotelRoom/repository/RoomThemeRepository.java
  src/main/java/com/yanolja/scbj/domain/member/controller/MemberAuthRestController.java
  src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberUpdatePasswordRequest.java
  src/main/java/com/yanolja/scbj/domain/member/entity/Member.java
  src/main/java/com/yanolja/scbj/domain/member/entity/MemberAgreement.java
  src/main/java/com/yanolja/scbj/domain/member/entity/YanoljaMember.java
  src/main/java/com/yanolja/scbj/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/yanolja/scbj/domain/member/repository/MemberRepository.java
  src/main/java/com/yanolja/scbj/domain/member/repository/YanoljaMemberRepository.java
  src/main/java/com/yanolja/scbj/domain/member/validation/Password.java
  src/main/java/com/yanolja/scbj/domain/member/validation/Phone.java
  src/main/java/com/yanolja/scbj/domain/member/validation/validator/PhoneValidator.java
  src/main/java/com/yanolja/scbj/domain/payment/entity/PaymentAgreement.java
  src/main/java/com/yanolja/scbj/domain/payment/entity/PaymentHistory.java
  src/main/java/com/yanolja/scbj/domain/payment/repository/PaymentAgreementRepository.java
  src/main/java/com/yanolja/scbj/domain/payment/repository/PaymentHistoryRepository.java
  src/main/java/com/yanolja/scbj/domain/product/entity/Product.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
  src/main/java/com/yanolja/scbj/domain/reservation/entity/Reservation.java
  src/main/java/com/yanolja/scbj/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/yanolja/scbj/global/common/BaseEntity.java
  src/main/java/com/yanolja/scbj/global/config/CustomUserDetailsService.java
  src/main/java/com/yanolja/scbj/global/config/SecurityConfig.java
  src/main/java/com/yanolja/scbj/global/config/jwt/JwtRequestFilter.java
  src/main/java/com/yanolja/scbj/global/config/jwt/JwtUtil.java
  src/main/java/com/yanolja/scbj/global/exception/ApplicationException.java
  src/main/java/com/yanolja/scbj/global/exception/GlobalRestControllerAdvice.java
  src/main/resources/application-local.yml
Labels: 🛠feature

#36 Feature/#35 response dto
  src/main/java/com/yanolja/scbj/global/common/ResponseDTO.java
Labels: 🛠feature

#39 feat: AlarmRepository 생성
  src/main/java/com/yanolja/scbj/domain/alarm/repository/AlarmRepository.java
Labels: 🛠feature

#43 fix: roomTheme 필드 값 변경
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/RoomTheme.java
Labels: fix

#45 member, yanoljamember, product entity 수정
  src/main/java/com/yanolja/scbj/domain/member/entity/Member.java
  src/main/java/com/yanolja/scbj/domain/member/entity/YanoljaMember.java
  src/main/java/com/yanolja/scbj/domain/product/entity/Product.java
Labels: fix

#46 fix: responseDTO에 code 중복 생성 제거
  src/main/java/com/yanolja/scbj/global/common/ResponseDTO.java
Labels: fix

#48 fix: base Entity 수정
  src/main/java/com/yanolja/scbj/ScbjApplication.java
  src/main/java/com/yanolja/scbj/global/common/BaseEntity.java
Labels: :lady_beetle: bug

#49 feat: security 테스트 헬퍼 클래스 작성
  src/test/java/com/yanolja/scbj/util/ControllerTestWithoutSecurityHelper.java
Labels: 🛠feature

#50 Feature/#37 find detail product
  src/main/java/com/yanolja/scbj/domain/hotelRoom/dto/response/RoomThemeFindResponse.java
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/Hotel.java
  src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java
  src/main/java/com/yanolja/scbj/domain/product/dto/ProductFindResponse.java
  src/main/java/com/yanolja/scbj/domain/product/entity/Product.java
  src/main/java/com/yanolja/scbj/domain/product/exception/ProductNotFoundException.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/main/java/com/yanolja/scbj/global/config/SecurityConfig.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
  src/main/java/com/yanolja/scbj/global/util/SeasonValidator.java
  src/test/java/com/yanolja/scbj/domain/product/controller/ProductRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
Labels: 🛠feature

#53 feat: security helper 클래스 삭제
  src/test/java/com/yanolja/scbj/util/ControllerTestWithoutSecurityHelper.java
Labels: fix

#56 Feature/#21 product create
  src/main/java/com/yanolja/scbj/domain/member/entity/Member.java
  src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java
  src/main/java/com/yanolja/scbj/domain/product/dto/request/ProductPostRequest.java
  src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductFindResponse.java
  src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductPostResponse.java
  src/main/java/com/yanolja/scbj/domain/product/exception/FirstPriceHigherException.java
  src/main/java/com/yanolja/scbj/domain/product/exception/SecondPriceHigherException.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/main/java/com/yanolja/scbj/domain/reservation/exception/ReservationNotFoundException.java
  src/main/java/com/yanolja/scbj/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
  src/test/java/com/yanolja/scbj/domain/product/controller/ProductRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
Labels: 🛠feature, fix

#60 fix: 패키지 오류 수정
  src/main/java/com/yanolja/scbj/domain/product/service/ProductDtoConverter.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductDtoConverterTest.java
Labels: fix

#62 Feature/#58 add post product exception
  src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java
  src/main/java/com/yanolja/scbj/domain/product/exception/SecondPricePeriodException.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
Labels: 🛠feature, 🩹refactor

#64 Feature/#55 product delete
  src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java
  src/main/java/com/yanolja/scbj/domain/product/entity/Product.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/test/java/com/yanolja/scbj/domain/product/controller/ProductRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
Labels: 🛠feature

#67 계정 등록 및 수정 API 구현 및 그 동안의 멤버 테스트 구현
  build.gradle
  src/main/java/com/yanolja/scbj/domain/member/controller/MemberAuthRestController.java
  src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java
  src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberSignInRequest.java
  src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberSignUpRequest.java
  src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberUpdateAccountRequest.java
  src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberUpdatePasswordRequest.java
  src/main/java/com/yanolja/scbj/domain/member/entity/Member.java
  src/main/java/com/yanolja/scbj/domain/member/entity/MemberAgreement.java
  src/main/java/com/yanolja/scbj/domain/member/service/MemberService.java
  src/main/java/com/yanolja/scbj/global/common/BaseEntity.java
  src/main/java/com/yanolja/scbj/global/config/SecurityConfig.java
  src/test/java/com/yanolja/scbj/domain/member/controller/MemberAuthRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/member/service/MemberAuthServiceTest.java
  src/test/java/com/yanolja/scbj/domain/member/service/MemberServiceTest.java
  src/test/java/com/yanolja/scbj/global/config/AbstractContainersSupport.java
Labels: 🛠feature, :test_tube: test

#68 feat: mysql 각 계정 연동을 위한 env 파일 생성
  .gitignore
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 🛠feature

#75 유저 이름 변경 API구현
  src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java
  src/main/java/com/yanolja/scbj/domain/member/entity/Member.java
  src/main/java/com/yanolja/scbj/domain/member/service/MemberService.java
  src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/member/service/MemberServiceTest.java
Labels: 🛠feature, :test_tube: test

#76 Feature/#69 fix product create notnull
  src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java
  src/main/java/com/yanolja/scbj/domain/product/dto/request/ProductPostRequest.java
  src/main/java/com/yanolja/scbj/domain/product/entity/Product.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/test/java/com/yanolja/scbj/domain/product/controller/ProductRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
Labels: 🛠feature, fix

#82 Feature/#37 fix find product
  src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductFindResponse.java
  src/main/java/com/yanolja/scbj/domain/product/enums/SecondTransferExistence.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductDtoConverter.java
Labels: 🛠feature, fix

#70 Feature/#40 purchased history (구매내역) 추가
  src/main/java/com/yanolja/scbj/domain/payment/dto/PurchasedHistoryResponse.java
  src/main/java/com/yanolja/scbj/domain/payment/entity/PaymentAgreement.java
  src/main/java/com/yanolja/scbj/domain/payment/entity/PaymentHistory.java
  src/main/java/com/yanolja/scbj/domain/payment/hisotryService/PurchasedHistoryService.java
  src/main/java/com/yanolja/scbj/domain/payment/historycontroller/PurchasedHistoryController.java
  src/main/java/com/yanolja/scbj/domain/payment/repository/PaymentHistoryRepository.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
  src/test/java/com/yanolja/scbj/domain/payment/hisotryService/PurchasedHistoryServiceTest.java
  src/test/java/com/yanolja/scbj/domain/payment/paymentController/PurchasedHistoryControllerTest.java
  src/test/java/com/yanolja/scbj/domain/payment/paymentController/PurchasedHistoryRestDocControllerTest.java
  src/test/java/com/yanolja/scbj/domain/payment/repository/PaymentHistoryRepositoryTest.java
Labels: 🛠feature, :test_tube: test

#78 회원 정보 조회 기능 구현
  src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java
  src/main/java/com/yanolja/scbj/domain/member/dto/response/MemberResponse.java
  src/main/java/com/yanolja/scbj/domain/member/service/MemberService.java
  src/main/java/com/yanolja/scbj/domain/member/util/MemberMapper.java
  src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/member/service/MemberServiceTest.java
Labels: 🛠feature, :test_tube: test

#77 유저 핸드폰 번호 변경 기능 구현
  src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java
  src/main/java/com/yanolja/scbj/domain/member/entity/Member.java
  src/main/java/com/yanolja/scbj/domain/member/service/MemberService.java
  src/main/java/com/yanolja/scbj/domain/member/validation/Phone.java
  src/main/java/com/yanolja/scbj/global/exception/GlobalRestControllerAdvice.java
  src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/member/service/MemberServiceTest.java
Labels: 🛠feature, :test_tube: test

#83 야놀자 계정 연동하기 기능 구현
  src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java
  src/main/java/com/yanolja/scbj/domain/member/dto/response/MemberResponse.java
  src/main/java/com/yanolja/scbj/domain/member/exception/NotFoundYanoljaMember.java
  src/main/java/com/yanolja/scbj/domain/member/repository/YanoljaMemberRepository.java
  src/main/java/com/yanolja/scbj/domain/member/service/MemberService.java
  src/main/java/com/yanolja/scbj/domain/member/util/MemberMapper.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
  src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/member/service/MemberServiceTest.java
Labels: 🛠feature, :test_tube: test

#79 이메일 인증 번호 발급 기능 구현
  build.gradle
  src/main/java/com/yanolja/scbj/domain/member/config/EmailConfig.java
  src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java
  src/main/java/com/yanolja/scbj/domain/member/exception/EmailServcerException.java
  src/main/java/com/yanolja/scbj/domain/member/service/MailService.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
  src/main/resources/application-local.yml
  src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/member/service/MailServiceTest.java
  src/test/resources/application.yml
Labels: 🛠feature, :test_tube: test

#92 PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :memo: documentation, fix

#90 상품 상세 조회시 이미지 값 추가
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/Hotel.java
  src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductFindResponse.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductDtoConverter.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductDtoConverterTest.java
Labels: 🛠feature, fix

#88 Feature/#86 create product 1.5sprint
  src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java
  src/main/java/com/yanolja/scbj/domain/product/dto/request/ProductPostRequest.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
Labels: 🛠feature, :test_tube: test

#87 Feature/#65 get yanolja reservation
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/Hotel.java
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/RefundPolicy.java
  src/main/java/com/yanolja/scbj/domain/hotelRoom/exception/RefundNotFoundException.java
  src/main/java/com/yanolja/scbj/domain/hotelRoom/repository/RefundPolicyRepository.java
  src/main/java/com/yanolja/scbj/domain/reservation/controller/ReservationRestController.java
  src/main/java/com/yanolja/scbj/domain/reservation/dto/response/ReservationFindResponse.java
  src/main/java/com/yanolja/scbj/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/yanolja/scbj/domain/reservation/service/ReservationDtoConverter.java
  src/main/java/com/yanolja/scbj/domain/reservation/service/ReservationService.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
  src/test/java/com/yanolja/scbj/domain/reservation/controller/ReservationRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationDtoConverterTest.java
  src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationServiceTest.java
Labels: 🛠feature, :test_tube: test

#99 회원 가입 시, 약관 생성
  src/main/java/com/yanolja/scbj/domain/member/entity/Member.java
  src/main/java/com/yanolja/scbj/domain/member/entity/MemberAgreement.java
  src/main/java/com/yanolja/scbj/domain/member/util/MemberMapper.java
Labels: 🛠feature, fix

#102 토큰 재발급 시, 액세스 토큰 만료 여부에 따라 안되던 로직 수정
  src/main/java/com/yanolja/scbj/domain/member/service/MemberAuthService.java
Labels: 🛠feature, fix

#95 글로벌 및 Security 예외 처리 수정
  src/main/java/com/yanolja/scbj/global/config/SecurityConfig.java
  src/main/java/com/yanolja/scbj/global/config/jwt/JwtRequestFilter.java
  src/main/java/com/yanolja/scbj/global/exception/GlobalRestControllerAdvice.java
Labels: fix

#97 유효성 처리 순서 명시
  src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java
  src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberEmailRequest.java
  src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberSignInRequest.java
  src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberSignUpRequest.java
  src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberUpdateAccountRequest.java
  src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberUpdateNameRequest.java
  src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberUpdatePasswordRequest.java
  src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberUpdatePhoneRequest.java
  src/main/java/com/yanolja/scbj/domain/member/dto/request/RefreshRequest.java
  src/main/java/com/yanolja/scbj/domain/member/validation/AccessToken.java
  src/main/java/com/yanolja/scbj/domain/member/validation/Password.java
  src/main/java/com/yanolja/scbj/domain/member/validation/Phone.java
  src/main/java/com/yanolja/scbj/domain/member/validation/ValidationGroups.java
  src/main/java/com/yanolja/scbj/domain/member/validation/ValidationSequence.java
  src/main/java/com/yanolja/scbj/domain/member/validation/validator/PasswordValidator.java
  src/main/java/com/yanolja/scbj/domain/member/validation/validator/PhoneValidator.java
  src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerTest.java
Labels: fix

#106 refactor: dto를 record로 변경
  src/main/java/com/yanolja/scbj/domain/product/dto/request/ProductPostRequest.java
  src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductPostResponse.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/main/java/com/yanolja/scbj/domain/reservation/dto/response/ReservationFindResponse.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
  src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationDtoConverterTest.java
  src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationServiceTest.java
Labels: :test_tube: test, 🩹refactor

#108 feat: 구매내역 조회 비즈니스 로직 구현
  src/main/java/com/yanolja/scbj/domain/payment/controller/HistoryController.java
  src/main/java/com/yanolja/scbj/domain/payment/dto/response/SpecificPurchasedHistoryResponse.java
  src/main/java/com/yanolja/scbj/domain/payment/exception/PaymentHistoryNotFoundException.java
  src/main/java/com/yanolja/scbj/domain/payment/repository/PaymentHistoryRepository.java
  src/main/java/com/yanolja/scbj/domain/payment/service/HistoryService.java
  src/main/java/com/yanolja/scbj/domain/payment/service/PaymentHistoryDtoConverter.java
Labels: 🛠feature

#104 멤버 서비스 응답 메시지 변경
  src/main/java/com/yanolja/scbj/domain/member/controller/MemberAuthRestController.java
  src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java
Labels: 🩹refactor

#119 1차 회고에 맞춰 수정
  src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java
  src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductFindResponse.java
  src/test/java/com/yanolja/scbj/domain/product/controller/ProductRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductDtoConverterTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
Labels: 🩹refactor

#123 비밀번호 수정 시, 액세스 토큰이 필요없기 때문에 email을 활용한 수정
  src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberUpdatePasswordRequest.java
  src/main/java/com/yanolja/scbj/domain/member/service/MemberService.java
  src/test/java/com/yanolja/scbj/domain/member/service/MemberServiceTest.java
Labels: 🛠feature, :test_tube: test, fix

#117 Feature/#110 find payment page
  src/main/java/com/yanolja/scbj/domain/payment/controller/PaymentRestController.java
  src/main/java/com/yanolja/scbj/domain/payment/dto/response/PaymentPageFindResponse.java
  src/main/java/com/yanolja/scbj/domain/payment/service/PaymentHistoryDtoConverter.java
  src/main/java/com/yanolja/scbj/domain/payment/service/PaymentService.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductDtoConverter.java
  src/main/java/com/yanolja/scbj/global/util/SeasonValidator.java
  src/main/java/com/yanolja/scbj/global/util/TimeValidator.java
Labels: 🛠feature, fix

#120 Feature/#107 get specific purchased history
  src/main/java/com/yanolja/scbj/domain/payment/service/PaymentHistoryDtoConverter.java
  src/test/java/com/yanolja/scbj/domain/payment/paymentController/HistoryControllerTest.java
  src/test/java/com/yanolja/scbj/domain/payment/repository/HistoryRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/payment/service/HistoryServiceTest.java
  src/test/java/com/yanolja/scbj/domain/payment/service/PaymentHistoryDtoConverterTest.java
Labels: :test_tube: test, 🩹refactor

#128 Feature/#126 fix reservation entity
  src/main/java/com/yanolja/scbj/domain/payment/dto/response/PurchasedHistoryResponse.java
  src/main/java/com/yanolja/scbj/domain/payment/dto/response/SaleHistoryResponse.java
  src/main/java/com/yanolja/scbj/domain/payment/service/PaymentService.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductDtoConverter.java
  src/main/java/com/yanolja/scbj/domain/reservation/dto/response/ReservationFindResponse.java
  src/main/java/com/yanolja/scbj/domain/reservation/entity/Reservation.java
  src/test/java/com/yanolja/scbj/domain/payment/paymentController/HistoryControllerTest.java
  src/test/java/com/yanolja/scbj/domain/payment/repository/HistoryRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/payment/service/HistoryServiceTest.java
  src/test/java/com/yanolja/scbj/domain/payment/service/PaymentHistoryDtoConverterTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductDtoConverterTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
  src/test/java/com/yanolja/scbj/domain/reservation/controller/ReservationRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationDtoConverterTest.java
  src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationServiceTest.java
Labels: 🛠feature, :test_tube: test, fix

#125 feat: 야놀자 크롤링 및 목데이터 생성
  build.gradle
  src/main/java/com/yanolja/scbj/domain/mockData/CreateMockData.java
Labels: 🛠feature

#114 Feature/#24 product inquire repository 구현
  .gitignore
  build.gradle
  src/main/java/com/yanolja/scbj/domain/product/dto/request/ProductPostRequest.java
  src/main/java/com/yanolja/scbj/domain/product/dto/request/ProductSearchRequest.java
  src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductSearchResponse.java
  src/main/java/com/yanolja/scbj/domain/product/entity/Product.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/main/java/com/yanolja/scbj/global/common/BaseEntity.java
  src/main/java/com/yanolja/scbj/global/config/QuerydslConfiguration.java
  src/test/java/com/yanolja/scbj/ScbjApplicationTests.java
  src/test/java/com/yanolja/scbj/domain/payment/repository/HistoryRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/payment/service/PaymentHistoryDtoConverterTest.java
  src/test/java/com/yanolja/scbj/domain/product/repository/ProductSearchRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
  src/test/java/com/yanolja/scbj/global/config/QuerydslConfig.java
Labels: 🛠feature

#131 feat: 카카오페이 결제 구현 완료
  src/main/java/com/yanolja/scbj/domain/payment/controller/PaymentRestController.java
  src/main/java/com/yanolja/scbj/domain/payment/dto/request/PaymentReadyRequest.java
  src/main/java/com/yanolja/scbj/domain/payment/dto/response/PaymentAmountResponse.java
  src/main/java/com/yanolja/scbj/domain/payment/dto/response/PaymentApproveResponse.java
  src/main/java/com/yanolja/scbj/domain/payment/dto/response/PaymentCancelResponse.java
  src/main/java/com/yanolja/scbj/domain/payment/dto/response/PaymentReadyResponse.java
  src/main/java/com/yanolja/scbj/domain/payment/entity/PaymentHistory.java
  src/main/java/com/yanolja/scbj/domain/payment/service/PaymentService.java
  src/main/resources/application-local.yml
Labels: 🛠feature, fix

#143 Feature/#115 search controller service 구현
  src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/test/java/com/yanolja/scbj/domain/product/controller/ProductRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/product/repository/ProductSearchRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
Labels: 🛠feature

#136 알람 조회 기능을 구현하다.
  src/main/java/com/yanolja/scbj/domain/alarm/controller/AlarmRestController.java
  src/main/java/com/yanolja/scbj/domain/alarm/dto/AlarmResponse.java
  src/main/java/com/yanolja/scbj/domain/alarm/entity/Alarm.java
  src/main/java/com/yanolja/scbj/domain/alarm/exception/AlarmNotFoundException.java
  src/main/java/com/yanolja/scbj/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/yanolja/scbj/domain/alarm/service/AlarmService.java
  src/main/java/com/yanolja/scbj/domain/alarm/util/AlarmMapper.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
Labels: 🛠feature

#137 알림 조회 테스트를 개발하다
  .gitignore
  src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java
  src/test/java/com/yanolja/scbj/domain/alarm/controller/AlarmRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/alarm/service/AlarmServiceTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
Labels: :test_tube: test

#150 test: 결제 페이지 조회 테스트 코드 작성
  src/test/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentServiceTest.java
Labels: :test_tube: test

#138 FireBase 세팅을 하다
  .github/workflows/deploy.yml
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  src/main/java/com/yanolja/scbj/global/config/AsyncConfig.java
  src/main/java/com/yanolja/scbj/global/config/RestConfig.java
  src/main/java/com/yanolja/scbj/global/config/SecurityConfig.java
  src/main/java/com/yanolja/scbj/global/config/fcm/FCMRequest.java
  src/main/java/com/yanolja/scbj/global/config/fcm/FCMService.java
  src/main/java/com/yanolja/scbj/global/config/fcm/FCMTokenRepository.java
  src/main/java/com/yanolja/scbj/global/config/fcm/FirebaseServerException.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
  src/main/java/com/yanolja/scbj/global/util/LocalDateTimeUtil.java
  src/main/resources/application-local.yml
  src/main/resources/static/firebase-messaging-sw.js
  src/test/java/com/yanolja/scbj/domain/fcm/FCMServiceTest.java
  src/test/java/com/yanolja/scbj/global/config/AbstractContainersSupport.java
  src/test/resources/application.yml
Labels: 🛠feature, :test_tube: test, fix

#152 Feature/#144 sale history detail 기능 구현
  src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentHistoryRestController.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/SpecificSaleHistoryResponse.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/exception/SaleHistoryNotFoundException.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryService.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/SaleHistoryDtoConverter.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
  src/test/java/com/yanolja/scbj/domain/fcm/FCMServiceTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/paymentController/PaymentHistoryRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryServiceTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/SaleHistoryDtoConverterTest.java
Labels: 🛠feature

#146 Feature/#145 fix get reservation remaining days
  build.gradle
  src/main/java/com/yanolja/scbj/domain/reservation/entity/Reservation.java
  src/main/java/com/yanolja/scbj/domain/reservation/service/ReservationDtoConverter.java
  src/main/java/com/yanolja/scbj/global/config/SecurityConfig.java
  src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationDtoConverterTest.java
Labels: 🛠feature, fix

#153 알림 생성 서비스 구현하다.
  src/main/java/com/yanolja/scbj/domain/alarm/service/AlarmService.java
  src/main/java/com/yanolja/scbj/domain/alarm/util/AlarmMapper.java
  src/main/java/com/yanolja/scbj/domain/member/service/MemberService.java
  src/main/resources/application-local.yml
  src/test/java/com/yanolja/scbj/domain/alarm/service/AlarmServiceTest.java
Labels: 🛠feature, :test_tube: test

#158 멤버 서비스, 에러 메시지 수정
  src/main/java/com/yanolja/scbj/domain/member/exception/EmailServcerException.java
  src/main/java/com/yanolja/scbj/domain/member/exception/EmailServerException.java
  src/main/java/com/yanolja/scbj/domain/member/exception/InvalidEmailAndPasswordException.java
  src/main/java/com/yanolja/scbj/domain/member/service/MailService.java
  src/main/java/com/yanolja/scbj/domain/member/service/MemberService.java
  src/main/java/com/yanolja/scbj/domain/member/validation/Password.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
Labels: fix

#156 Fix/#155 fix search product
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
  src/test/java/com/yanolja/scbj/domain/product/repository/ProductSearchRepositoryTest.java
Labels: 🛠feature, fix

#160 알람에 읽음 여부를 추가합니다!!
  src/main/java/com/yanolja/scbj/domain/alarm/dto/AlarmResponse.java
  src/main/java/com/yanolja/scbj/domain/alarm/entity/Alarm.java
  src/main/java/com/yanolja/scbj/domain/alarm/service/AlarmService.java
  src/main/java/com/yanolja/scbj/domain/alarm/util/AlarmMapper.java
  src/test/java/com/yanolja/scbj/domain/alarm/controller/AlarmRestControllerTest.java
Labels: 🛠feature, :test_tube: test

#166 jwt parsing시 발생할 수 있는 base64 예외 핸들링 및및 error code 수정
  src/main/java/com/yanolja/scbj/global/config/jwt/JwtRequestFilter.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
Labels: fix

#169 jwtUtill 사용 시, 권한이 없는 유저에 대해 예외 처리 추가
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
  src/main/java/com/yanolja/scbj/global/exception/ForbbidenException.java
  src/main/java/com/yanolja/scbj/global/util/SecurityUtil.java
Labels: 🛠feature, fix

#170 FCM 서버 예외 시, 재시도 및 메일 전송 보상 처리
  build.gradle
  src/main/java/com/yanolja/scbj/domain/member/service/MailService.java
  src/main/java/com/yanolja/scbj/global/config/RetryConfig.java
  src/main/java/com/yanolja/scbj/global/config/fcm/FCMService.java
  src/test/java/com/yanolja/scbj/domain/fcm/FCMIntegrationTest.java
  src/test/java/com/yanolja/scbj/domain/fcm/FCMServiceTest.java
  src/test/java/com/yanolja/scbj/global/config/AbstractContainersSupport.java
Labels: 🛠feature, :test_tube: test

#172 계좌 번호 관련 유효성 추가
  src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberUpdateAccountRequest.java
  src/test/java/com/yanolja/scbj/domain/member/controller/MemberRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/member/service/MemberServiceTest.java
Labels: 🛠feature, :test_tube: test, fix

#175 Feature/#163 main page
  src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java
  src/main/java/com/yanolja/scbj/domain/product/dto/request/ProductCityRequest.java
  src/main/java/com/yanolja/scbj/domain/product/dto/response/CityResponse.java
  src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductMainResponse.java
  src/main/java/com/yanolja/scbj/domain/product/dto/response/WeekendProductResponse.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
  src/main/java/com/yanolja/scbj/domain/product/service/CityDtoConverter.java
  src/main/java/com/yanolja/scbj/domain/product/service/PricingHelper.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/main/java/com/yanolja/scbj/domain/product/service/WeekendDtoConverter.java
  src/test/java/com/yanolja/scbj/domain/product/controller/ProductRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/product/repository/ProductMainRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/product/repository/ProductSearchRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductMainDtoTest.java
  src/test/java/com/yanolja/scbj/domain/testdata/TestData.java
Labels: 🛠feature, 🩹refactor

#174 알림 도메인 LocalDateTime으로 반환 수정
  src/main/java/com/yanolja/scbj/domain/alarm/dto/AlarmResponse.java
  src/main/java/com/yanolja/scbj/global/config/fcm/FCMRequest.java
  src/main/java/com/yanolja/scbj/global/util/LocalDateTimeUtil.java
  src/test/java/com/yanolja/scbj/domain/alarm/service/AlarmServiceTest.java
  src/test/java/com/yanolja/scbj/domain/fcm/FCMIntegrationTest.java
Labels: fix

#182 결제 로직 수정 + 보완
  src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestController.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/exception/ProductNotForSaleException.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java
  src/main/java/com/yanolja/scbj/domain/product/entity/Product.java
  src/main/java/com/yanolja/scbj/global/config/RetryConfig.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
  src/main/java/com/yanolja/scbj/global/exception/InternalServerException.java
  src/main/resources/application-local.yml
Labels: 🛠feature, fix

#179 Fix/#178 fix sale history inquire
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/SaleHistoryResponse.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/paymentController/PaymentHistoryRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryServiceTest.java
Labels: 🩹refactor, fix

#185 FE 푸쉬 알림 TEST용 Controller 생성
  build.gradle
  src/main/java/com/yanolja/scbj/global/config/fcm/FCMController.java
  src/main/java/com/yanolja/scbj/global/config/fcm/FCMRestController.java
  src/main/resources/templates/FcmTest.html
Labels: 🛠feature

#192 토큰 재발급 시, 유효한 액세스 토큰에 대한 유효성 처리
  src/main/java/com/yanolja/scbj/domain/member/exception/NotExpiredTokenException.java
  src/main/java/com/yanolja/scbj/domain/member/service/MemberAuthService.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
Labels: 🛠feature

#190 Refactor/#189refactor main page
  src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/main/java/com/yanolja/scbj/domain/product/service/WeekendDtoConverter.java
  src/test/java/com/yanolja/scbj/domain/product/controller/ProductRestControllerTest.java
Labels: 🩹refactor

#188 결제 로직 일부 리팩토링했습니드아
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/request/PaymentReadyRequest.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java
Labels: 🩹refactor

#195 refactor: 이미지로 인한 중복상품 생성으로 인한 리팩토링
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
Labels: 🛠feature

#187 정산, 알람 추가
  build.gradle
  src/main/java/com/yanolja/scbj/domain/paymentHistory/entity/PaymentHistory.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/repository/PaymentHistoryRepository.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/SettlementService.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/repository/HistoryRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/testdata/TestData.java
  src/test/resources/application.yml
Labels: 🛠feature

#199 상세 조회 시 상품 판매자 체크 로직 추가
  src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductFindResponse.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductDtoConverter.java
  src/main/java/com/yanolja/scbj/global/util/SecurityUtil.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductDtoConverterTest.java
Labels: 🛠feature, fix

#202 Refactor/#201refactor search
  src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
  src/test/java/com/yanolja/scbj/domain/product/controller/ProductRestControllerTest.java
Labels: 🩹refactor

#204 Refactor/#203 refactor main page
  src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java
  src/main/java/com/yanolja/scbj/domain/product/dto/request/ProductCityRequest.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/test/java/com/yanolja/scbj/domain/product/controller/ProductRestControllerTest.java
Labels: 🩹refactor, fix

#209 Refactor/#208 refactor search page problem
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
  src/test/java/com/yanolja/scbj/domain/product/repository/ProductSearchRepositoryTest.java
Labels: 🩹refactor, fix

#208 fix: product entity 수정으로 stock 1로 수정
  src/main/java/com/yanolja/scbj/domain/product/entity/Product.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
Labels: fix

#206 Feature/#200 fix get reservation with non product
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
  src/main/java/com/yanolja/scbj/domain/reservation/service/ReservationDtoConverter.java
  src/main/java/com/yanolja/scbj/domain/reservation/service/ReservationService.java
  src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationDtoConverterTest.java
Labels: 🛠feature, fix

#196 로그인 및 로그아웃 시 fcm token 저장 및 삭제
  src/main/java/com/yanolja/scbj/domain/member/dto/request/MemberSignInRequest.java
  src/main/java/com/yanolja/scbj/domain/member/service/MemberAuthService.java
  src/main/java/com/yanolja/scbj/domain/member/service/MemberService.java
  src/main/java/com/yanolja/scbj/global/config/fcm/FCMService.java
  src/main/java/com/yanolja/scbj/global/config/jwt/exception/InvalidTokenException.java
  src/test/java/com/yanolja/scbj/domain/member/service/MemberAuthServiceTest.java
  src/test/java/com/yanolja/scbj/domain/member/service/MemberServiceTest.java
Labels: 🛠feature

#217 feat: 결제 약관 엔티티 속성 추가
  src/main/java/com/yanolja/scbj/domain/paymentHistory/entity/PaymentAgreement.java
Labels: 🛠feature

#214 Feature/#212 has non read alarm
  src/main/java/com/yanolja/scbj/domain/alarm/controller/AlarmRestController.java
  src/main/java/com/yanolja/scbj/domain/alarm/dto/AlarmHasNonReadResponse.java
  src/main/java/com/yanolja/scbj/domain/alarm/entity/Alarm.java
  src/main/java/com/yanolja/scbj/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/yanolja/scbj/domain/alarm/service/AlarmService.java
  src/main/java/com/yanolja/scbj/domain/alarm/util/AlarmMapper.java
  src/main/java/com/yanolja/scbj/global/config/jwt/JwtRequestFilter.java
  src/main/resources/application-local.yml
  src/test/java/com/yanolja/scbj/domain/alarm/controller/AlarmRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/alarm/service/AlarmServiceTest.java
Labels: 🛠feature, :test_tube: test

#218 feat: product, productAgreement entity 생성
  src/main/java/com/yanolja/scbj/domain/product/entity/Product.java
  src/main/java/com/yanolja/scbj/domain/product/entity/ProductAgreement.java
Labels: 🛠feature

#220 계좌 등록 시, 연동된 계정이어야 합니다.
  src/main/java/com/yanolja/scbj/domain/member/service/MemberService.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
  src/main/java/com/yanolja/scbj/global/exception/IsNotYanoljaMemberException.java
  src/test/java/com/yanolja/scbj/domain/member/service/MemberServiceTest.java
Labels: 🛠feature, fix

#219 feat: 컬럼의 기본 값 추가
  src/main/java/com/yanolja/scbj/domain/paymentHistory/entity/PaymentAgreement.java
Labels: 🛠feature

#224 REDISSON 의존성이 생김에 따른 CI, CD 스크립트를 추가합니다.
  .github/workflows/deploy.yml
  .github/workflows/gradle.yml
  docker-compose.yml
Labels: hotfix

#222 fix: product, productAgreement 수정에 따른 양도글 작성 로직 변경
  src/main/java/com/yanolja/scbj/domain/product/dto/request/ProductPostRequest.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
Labels: 🛠feature, fix

#225 Fix/#221 fix history response
  src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentHistoryRestController.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/repository/PaymentHistoryRepository.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryService.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/paymentController/PaymentHistoryRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/repository/HistoryRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryServiceTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/SaleHistoryDtoConverterTest.java
Labels: fix

#210 결제 시 동시성 이슈 처리
  build.gradle
  src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestController.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/PaymentCancelResponse.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/PaymentReadyResponse.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/exception/ProductOutOfStockException.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/PaymentApiService.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
  src/main/resources/application-local.yml
  src/test/java/com/yanolja/scbj/ScbjApplicationTests.java
  src/test/resources/application.yml
Labels: 🛠feature, fix

#229 fix: 페이지네이션 문제로 인한 테스트
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
Labels: fix

#227 CI, CD redis container 삭제
  .github/workflows/deploy.yml
  .github/workflows/gradle.yml
Labels: fix

#231 결제 로직 테스트 코드 작성
  src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestController.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/request/PaymentReadyRequest.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/PaymentReadyResponse.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/PreparePaymentResponse.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/PaymentApiService.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/KakaoPaymentServiceTest.java
Labels: 🛠feature, :test_tube: test, 🩹refactor

#239 Refactor/#238 refactor search
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
Labels: 🩹refactor, fix

#240 fix: alias Exception 으로 인한 수정
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
Labels: fix, hotfix

#241 fix: baseEnttiy로 인한 수정
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
Labels: fix

#233 fix: responseDTO 수정
  src/main/java/com/yanolja/scbj/global/common/ResponseDTO.java
Labels: fix

#245 fix: 네이티브 쿼리 수정
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
Labels: fix

#247 Feature/#244 check product stock
  src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java
  src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductStockResponse.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/test/java/com/yanolja/scbj/domain/product/controller/ProductRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
Labels: 🛠feature

#250 fix: 네이티브 쿼리 오류 해결
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
Labels: fix

#249 크롤러 어플리케이션 분리
  build.gradle
  src/main/java/com/yanolja/scbj_crawling/CrawlerApplication.java
  src/main/java/com/yanolja/scbj_crawling/mockData/CreateMockData.java
Labels: 🛠feature

#254 hotfix: 크롤러 어플리케이션 삭제
  build.gradle
  src/main/java/com/yanolja/scbj_crawling/CrawlerApplication.java
  src/main/java/com/yanolja/scbj_crawling/mockData/CreateMockData.java
Labels: fix

#251 refactor: main 페이지 전채 수정
  src/main/java/com/yanolja/scbj/domain/product/controller/ProductRestController.java
  src/main/java/com/yanolja/scbj/domain/product/service/CityDtoConverter.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
Labels: 🩹refactor

#256 fix: SELECT 문 추가
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
Labels: 🩹refactor

#252 판매 가능 상품인지 체크하는 로직 수정
  src/main/java/com/yanolja/scbj/domain/product/service/ProductDtoConverter.java
Labels: fix

#258 refactor: 양도글(상품) 작성 리팩토링 완료
  src/main/java/com/yanolja/scbj/domain/member/util/MemberMapper.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/main/java/com/yanolja/scbj/domain/product/util/ProductMapper.java
Labels: 🩹refactor

#243 정산 시 벌크연산 도입
  src/main/java/com/yanolja/scbj/domain/paymentHistory/repository/PaymentHistoryRepository.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/SettlementService.java
  src/main/java/com/yanolja/scbj/global/config/SchedulerConfig.java
  src/main/resources/application-local.yml
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/SettlementServiceTest.java
  src/test/resources/application.yml
Labels: 🛠feature, :test_tube: test

#255 크롤링 어플리케이션 분리
  build.gradle
  src/main/java/com/yanolja/scbj_crawling/CrawlerApplication.java
  src/main/java/com/yanolja/scbj_crawling/mockData/CreateMockData.java
Labels: 🛠feature

#260 hotfix 결제 시 약관 추가
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/request/PaymentReadyRequest.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java
Labels: fix

#262 Refactor/#238 refactor search
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/test/java/com/yanolja/scbj/domain/product/controller/ProductRestControllerTest.java
Labels: 🩹refactor

#261 fix: 체크인 지났는지 확인 로직 수정
  src/main/java/com/yanolja/scbj/domain/product/service/ProductDtoConverter.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductDtoConverterTest.java
Labels: fix

#263 feat: isOverAge json property 추가
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/request/PaymentReadyRequest.java
Labels: 🛠feature

#265 Refactor/#238 refactor search
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/Hotel.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
  src/test/java/com/yanolja/scbj/domain/product/repository/ProductSearchRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/testdata/TestData.java
Labels: 🩹refactor

#267 hotFix: brunch 로 변경
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
Labels: hotfix

#268 Hotfix/set front url
  src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestController.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/PaymentApiService.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/KakaoPaymentServiceTest.java
Labels: fix

#266 상품 상세 조회 로직 리팩토링
  src/main/java/com/yanolja/scbj/domain/hotelRoom/util/RoomThemeMapper.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductDtoConverter.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/main/java/com/yanolja/scbj/domain/product/util/ProductMapper.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductDtoConverterTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
Labels: 🩹refactor

#269 hotFix: 날짜 필터링 수정
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
Labels: :lady_beetle: bug

#273 hotfix 2차양도 가격 설정 체크 로직 수정
  src/main/java/com/yanolja/scbj/global/util/TimeValidator.java
Labels: hotfix

#276 체크인 24시간 전 알림 구현
  src/main/java/com/yanolja/scbj/domain/alarm/dto/CheckInAlarmResponse.java
  src/main/java/com/yanolja/scbj/domain/alarm/service/AlarmService.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/entity/PaymentHistory.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/repository/PaymentHistoryRepository.java
  src/main/resources/application-local.yml
  src/test/java/com/yanolja/scbj/domain/alarm/repository/AlarmRepositoryTest.java
Labels: 🛠feature, :test_tube: test

#271 Feature/#259 refactor get reservation
  src/main/java/com/yanolja/scbj/domain/reservation/controller/ReservationRestController.java
  src/main/java/com/yanolja/scbj/domain/reservation/service/ReservationDtoConverter.java
  src/main/java/com/yanolja/scbj/domain/reservation/service/ReservationService.java
  src/main/java/com/yanolja/scbj/domain/reservation/util/ReservationMapper.java
  src/test/java/com/yanolja/scbj/domain/reservation/controller/ReservationRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationDtoConverterTest.java
  src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationServiceTest.java
Labels: :test_tube: test, 🩹refactor

#275 Feature/#274 main refactor
  src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentHistoryRestController.java
  src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductSearchResponse.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/yanolja/scbj/domain/product/service/CityDtoConverter.java
  src/main/java/com/yanolja/scbj/domain/product/service/CityMapper.java
  src/main/java/com/yanolja/scbj/domain/product/service/PricingHelper.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/main/java/com/yanolja/scbj/domain/product/service/WeekendDtoConverter.java
  src/main/java/com/yanolja/scbj/domain/product/service/WeekendMapper.java
  src/test/java/com/yanolja/scbj/domain/product/controller/ProductRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductMainDtoTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
Labels: 🩹refactor

#277 Hotfix: 메인페이지 퍼센트 계산 로직 변경
  src/main/java/com/yanolja/scbj/domain/product/service/PricingHelper.java
Labels: hotfix

#278 HotFIx: 2차가격 보여지는 문제 해결
  src/main/java/com/yanolja/scbj/domain/product/service/PricingHelper.java
Labels: hotfix

#279 Hotfix 2차 양도가겨 변경 시점 수정
  src/main/java/com/yanolja/scbj/global/util/TimeValidator.java
Labels: hotfix

#281 결제 시 반환 값 추가
  src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestController.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/PaymentSuccessResponse.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/PaymentApiService.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestControllerTest.java
Labels: 🛠feature, fix

#284 Feature/#272 refactor get payment history
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryDtoConverter.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryService.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/util/PaymentHistoryMapper.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryDtoConverterTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryServiceTest.java
Labels: 🩹refactor

#285 Hotfix: 할인순 정렬, 테마 정렬
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/test/java/com/yanolja/scbj/domain/product/repository/ProductMainRepositoryTest.java
Labels: hotfix

#287 HotFIx: 우선순위 변경
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
Labels: hotfix

#286 결제 로직 리팩토링
  src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestController.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/request/redis/PaymentRedisRequest.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/KakaoPayAmountResponse.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/KakaoPayApproveResponse.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/KakaoPayCancelResponse.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/KakaoPayReadyResponse.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/redis/PaymentRedisResponse.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/util/PaymentAgreementMapper.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/util/PaymentHistoryMapper.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/util/PaymentRedisMapper.java
  src/main/java/com/yanolja/scbj/domain/product/entity/Product.java
  src/main/java/com/yanolja/scbj/domain/product/util/ProductMapper.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/KakaoPaymentServiceTest.java
Labels: 🛠feature, 🩹refactor

#289 restdocs 설정
  build.gradle
  src/docs/asciidoc/product/product-api.adoc
  src/test/java/com/yanolja/scbj/docs/RestDocsConfig.java
  src/test/java/com/yanolja/scbj/docs/RestDocsSupport.java
Labels: 🛠feature, :test_tube: test

#293 fix: dto 통합
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/redis/PaymentRedisDto.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/redis/PaymentRedisResponse.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/util/PaymentAgreementMapper.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/util/PaymentHistoryMapper.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/util/PaymentRedisMapper.java
  src/main/java/com/yanolja/scbj/domain/product/util/ProductMapper.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/KakaoPaymentServiceTest.java
Labels: hotfix

#294 fix: url 수정
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java
Labels: hotfix

#295 구매 내역이 저장되기 이전에 알림 생성 서비스가 실행되는 거 방지
  src/main/java/com/yanolja/scbj/domain/alarm/service/AlarmService.java
Labels: hotfix

#296 알람 비동기 executor 명시
  src/main/java/com/yanolja/scbj/global/config/fcm/FCMService.java
Labels: 🛠feature, hotfix

#297 hotfix:알람 생성 비동기화
  src/main/java/com/yanolja/scbj/domain/alarm/service/AlarmService.java
Labels: hotfix

#298 hotfix: create Alarm 같은 쓰레드가 당담하게 변경
  src/main/java/com/yanolja/scbj/domain/alarm/service/AlarmService.java
Labels: hotfix

#301 Hotfix: 쿼리 수정
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
Labels: hotfix

#302 Hotfix: paymentHistory.createdAt 으로 수정
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/SaleHistoryDtoConverter.java
Labels: hotfix

#303 Update ProductRepository.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
Labels: hotfix

#304 hotfix: 쿼리 수정
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
Labels: hotfix

#305 Hotfix: 로직변경
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/SaleHistoryResponse.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/paymentController/PaymentHistoryRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryServiceTest.java
Labels: hotfix

#306 Hotfix: roomName 변경
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
Labels: hotfix

#307 Hotfix: getRoomName 으로 변경
  src/main/java/com/yanolja/scbj/domain/product/service/CityMapper.java
  src/main/java/com/yanolja/scbj/domain/product/service/WeekendMapper.java
Labels: hotfix

#308 Hot fix/payment history
  src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentHistoryRestController.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryService.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/SaleHistoryDtoConverter.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/paymentController/PaymentHistoryRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryServiceTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/SaleHistoryDtoConverterTest.java
Labels: 🩹refactor, hotfix

#313 hotFix: 판매목록과 하루차이나는 문제 해결
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/SaleHistoryDtoConverter.java
Labels: hotfix

#314 푸쉬 알림 상태 확인을 위한 로깅
  src/main/java/com/yanolja/scbj/domain/member/controller/MemberRestController.java
  src/main/java/com/yanolja/scbj/global/config/fcm/FCMService.java
Labels: hotfix

#317 체크인 알림 관련 test/**/ application.yml 환경 변수 추가
  src/test/resources/application.yml
Labels: fix

#315 결제 페이지 조회 로직 리팩토링
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentService.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/util/PaymentHistoryMapper.java
Labels: 🩹refactor

#319 Feature/#291 get reservation rest docs
  src/docs/asciidoc/reservation/reservation-api.adoc
  src/test/java/com/yanolja/scbj/docs/RestDocsSupport.java
  src/test/java/com/yanolja/scbj/domain/reservation/docs/ReservationRestControllerDocsTest.java
Labels: :memo: documentation

#321 상품 상세 조회 restdocs
  src/docs/asciidoc/product/product-api.adoc
  src/test/java/com/yanolja/scbj/docs/RestDocsSupport.java
  src/test/java/com/yanolja/scbj/domain/product/docs/ProductRestControllerDocsTest.java
Labels: :memo: documentation

#324 docs: 구매내역 상세 조회 api RESTDOCS 작업
  src/docs/asciidoc/paymentHistory/paymentHistory-api.adoc
  src/test/java/com/yanolja/scbj/domain/paymentHistory/docs/PaymentHistoryRestControllerDocsTest.java
Labels: :memo: documentation

#329 hotFix: 파라미터 값 수정
  src/main/java/com/yanolja/scbj/domain/paymentHistory/repository/PaymentHistoryRepository.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryService.java
Labels: hotfix

#326 hotfix: 판매내역 삭제시, 예약내역에 다시 보여주도록 수정
  src/main/java/com/yanolja/scbj/domain/reservation/service/ReservationService.java
  src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationServiceTest.java
Labels: hotfix

#330 결제 페이지 조회 restdocs 작성
  src/docs/asciidoc/paymentHistory/paymentHistory-api.adoc
  src/test/java/com/yanolja/scbj/domain/paymentHistory/docs/PaymentHistoryRestControllerDocsTest.java
  src/test/resources/application.yml
Labels: :memo: documentation
