Repository SCBJ-7/SCBJ-BE, pull requests merged in 2024-06, with the labels that each got.

#390 Feature/#371 find detail product v2
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/RoomTheme.java
  src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductFindResponse.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/main/java/com/yanolja/scbj/domain/product/util/ProductMapper.java
  src/test/java/com/yanolja/scbj/domain/product/docs/ProductRestControllerDocsTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
Labels: 🛠feature

#391 상품 상세 조회 v2
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
Labels: 🩹refactor, fix

#393 상세 조회 v2 수정
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
Labels: fix

#387 Feature/#386 create product v2
  src/main/java/com/yanolja/scbj/domain/product/dto/request/ProductPostRequest.java
  src/main/java/com/yanolja/scbj/domain/product/entity/Product.java
  src/main/java/com/yanolja/scbj/domain/product/util/ProductMapper.java
  src/main/java/com/yanolja/scbj/domain/product/util/StringListConverter.java
  src/main/resources/application-local.yml
  src/test/java/com/yanolja/scbj/domain/product/docs/ProductRestControllerDocsTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
Labels: 🛠feature, fix

#395 fix: converter 수정으로 null 제거
  src/main/java/com/yanolja/scbj/domain/product/util/StringListConverter.java
Labels: fix

#396 상품 상세 조회 시 판매자 코멘트 추가
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/main/java/com/yanolja/scbj/domain/product/util/ProductMapper.java
Labels: fix
