Repository SCBJ-7/SCBJ-BE, pull requests merged in 2024-04, with the labels that each got.

#358 Refactor/main refactoring
  src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentHistoryRestController.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/PaymentHistoryService.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/SaleHistoryDtoConverter.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepository.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/SaleHistoryDtoConverterTest.java
  src/test/java/com/yanolja/scbj/domain/product/repository/ProductSearchRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationServiceTest.java
Labels: 🩹refactor

#361 추가 크롤링
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/Hotel.java
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/Room.java
  src/main/java/com/yanolja/scbj_crawling/dto/response/RoomRatingResponse.java
  src/main/java/com/yanolja/scbj_crawling/mockData/CreateMockData.java
  src/test/java/com/yanolja/scbj/domain/alarm/repository/AlarmRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/repository/HistoryRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/SaleHistoryDtoConverterTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/SettlementServiceTest.java
  src/test/java/com/yanolja/scbj/domain/product/repository/ProductSearchRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/reservation/service/ReservationServiceTest.java
  src/test/java/com/yanolja/scbj/domain/testdata/TestData.java
Labels: 🛠feature, fix

#363 Fix/#362 fix search domain add stars and show every thing
  src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductSearchResponse.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
  src/test/java/com/yanolja/scbj/domain/product/docs/ProductRestControllerDocsTest.java
  src/test/java/com/yanolja/scbj/domain/product/repository/ProductSearchRepositoryTest.java
Labels: 🛠feature, fix

#365 객실 기본정보 크롤링 추가
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/Room.java
  src/main/java/com/yanolja/scbj_crawling/dto/response/RoomRatingResponse.java
  src/main/java/com/yanolja/scbj_crawling/mockData/CreateMockData.java
  src/test/java/com/yanolja/scbj/domain/alarm/repository/AlarmRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/repository/HistoryRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/SettlementServiceTest.java
  src/test/java/com/yanolja/scbj/domain/testdata/TestData.java
Labels: 🛠feature, fix

#366 크롤링 코드 수정 및 객실 엔티티 수정
  src/main/java/com/yanolja/scbj/domain/hotelRoom/entity/Room.java
  src/main/java/com/yanolja/scbj_crawling/dto/response/RoomInfoResponse.java
  src/main/java/com/yanolja/scbj_crawling/mockData/CreateMockData.java
Labels: fix

#368 hotfix: 도커 명령어 수정
  .github/workflows/deploy.yml
Labels: hotfix

#370 Feature/#369 add hotel review hotel rate
  src/main/java/com/yanolja/scbj/domain/product/dto/response/ProductSearchResponse.java
  src/main/java/com/yanolja/scbj/domain/product/repository/ProductRepositoryImpl.java
  src/test/java/com/yanolja/scbj/domain/product/repository/ProductMainRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/product/repository/ProductSearchRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/testdata/TestData.java
Labels: 🛠feature, fix

#373 Feature/#369 add hotel review hotel rate
  src/main/java/com/yanolja/scbj/domain/product/dto/response/CityResponse.java
  src/main/java/com/yanolja/scbj/domain/product/dto/response/WeekendProductResponse.java
  src/main/java/com/yanolja/scbj/domain/product/service/CityMapper.java
  src/main/java/com/yanolja/scbj/domain/product/service/ProductService.java
  src/main/java/com/yanolja/scbj/domain/product/service/WeekendMapper.java
  src/test/java/com/yanolja/scbj/domain/product/repository/ProductMainRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductMainDtoTest.java
  src/test/java/com/yanolja/scbj/domain/product/service/ProductServiceTest.java
Labels: 🛠feature, :test_tube: test, 🩹refactor

#376 카카오 페이 환불
  src/main/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestController.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/dto/response/KakaoPayRefundResponse.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/entity/PaymentHistory.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/repository/PaymentHistoryRepository.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/KaKaoPaymentService.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/service/paymentApi/PaymentApiService.java
  src/main/java/com/yanolja/scbj/domain/paymentHistory/util/PaymentHistoryMapper.java
  src/main/java/com/yanolja/scbj/global/exception/ErrorCode.java
  src/test/java/com/yanolja/scbj/domain/alarm/repository/AlarmRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/controller/PaymentRestControllerTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/repository/HistoryRepositoryTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/KakaoPaymentServiceTest.java
  src/test/java/com/yanolja/scbj/domain/paymentHistory/service/SettlementServiceTest.java
  src/test/java/com/yanolja/scbj/domain/testdata/TestData.java
Labels: 🛠feature, :test_tube: test

#379 Feature: 찜 엔티티 추가
  src/main/java/com/yanolja/scbj/domain/like/entity/Favorite.java
Labels: 🛠feature

#380 Update: Favorite 엔티티 수정
  src/main/java/com/yanolja/scbj/domain/like/entity/Favorite.java
Labels: fix
